"""add foreign key to onboarding

Revision ID: bc46828119fb
Revises: fd227cc1ae8c
Create Date: 2024-10-14 10:45:35.737463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc46828119fb'
down_revision = 'fd227cc1ae8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardings') as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_onboardings_employee', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardings') as batch_op:
        batch_op.drop_constraint('fk_onboardings_employee', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
