"""add foreign key to Review

Revision ID: fd227cc1ae8c
Revises: 098090b53acd
Create Date: 2024-10-14 01:05:45.791140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd227cc1ae8c'
down_revision = '098090b53acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_employee', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.drop_constraint('fk_reviews_employee', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
